### ISSUE TITLE
Polymer not minifiing

### ISSUE THREAD

**Issue by Ninerian** [AndreasGalster/lit-tutorial#1]
Hello,

thanks for this tutorial. It gives an good introduction to polymer and lit-html. 
After I finished it, I tried to produce a production build, to see the final size of the files. 

But I don't get Polymer to minify and concatenate all files,  as if I would get it with tools like webpack. Also the tagged literals are not minified at all.

Could you give me a hint, if this is an intended behaviour or how I could archive a correct build?

**Comment by AndreasGalster** [comment]
Sorry I usually do not use the Polymer CLI (I use Webpack in prod) but I'm sure @justinfagnani can answer this.

If I'm not mistaken the Polymer CLI is not yet 100% compatible with certain new 3.0 features.

Can you give reproduction steps how you created your production build? Is there a polymer.json file in your project?

**Comment by Ninerian** [comment]
I tested different build settings from the documentation of Polymer. An example is

```
{
"builds": [{
    "name": "bundled",
    "bundle": true,
    "js": {"minify": true},
    "css": {"minify": true},
    "html": {"minify": true}
  },{
    "name": "unbundled",
    "js": {"minify": true},
    "css": {"minify": true},
    "html": {"minify": true}
  }]
}
```

There is hardly a difference in the Output.
